#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _CaDynamics_reg(void);
extern void _Ca_HVA_reg(void);
extern void _Ca_LVA_reg(void);
extern void _Gfluct_new_exc_reg(void);
extern void _Gfluct_new_inh_reg(void);
extern void _Ih_reg(void);
extern void _Im_v2_reg(void);
extern void _K_P_reg(void);
extern void _K_T_reg(void);
extern void _Kd_reg(void);
extern void _Kv2like_reg(void);
extern void _Kv3_1_reg(void);
extern void _MyExp2Sid_reg(void);
extern void _NaTa_reg(void);
extern void _NaTs_reg(void);
extern void _NaV_reg(void);
extern void _OLM_IA_reg(void);
extern void _OLM_Ih_reg(void);
extern void _OLM_Lca_reg(void);
extern void _OLM_cat_reg(void);
extern void _OLM_ccanl_reg(void);
extern void _OLM_ichan2_reg(void);
extern void _OLM_nap_reg(void);
extern void _OLM_sahp_reg(void);
extern void _SK_reg(void);
extern void _bg2pyr_reg(void);
extern void _ca_reg(void);
extern void _cad_reg(void);
extern void _cadyn_reg(void);
extern void _cal2_reg(void);
extern void _capool_reg(void);
extern void _cav31_reg(void);
extern void _function_TMonitor_reg(void);
extern void _gabaa_reg(void);
extern void _gap_reg(void);
extern void _h_reg(void);
extern void _halfgap_reg(void);
extern void _im_reg(void);
extern void _int2intFENG_reg(void);
extern void _int2pyrFENG_reg(void);
extern void _int2pyrKIM_reg(void);
extern void _kadist_reg(void);
extern void _kaprox_reg(void);
extern void _kca_reg(void);
extern void _kdrca1_reg(void);
extern void _kdrca1DA_reg(void);
extern void _kdrinter_reg(void);
extern void _kdrinter_WB_reg(void);
extern void _km_reg(void);
extern void _kv_reg(void);
extern void _leak_reg(void);
extern void _leakDA_reg(void);
extern void _leakinter_reg(void);
extern void _na_reg(void);
extern void _na12_reg(void);
extern void _na16_reg(void);
extern void _na3_reg(void);
extern void _na3DA_reg(void);
extern void _nainter_reg(void);
extern void _nainter_WB_reg(void);
extern void _nap_reg(void);
extern void _nap2_reg(void);
extern void _nat_reg(void);
extern void _pyr2intFENG_reg(void);
extern void _pyr2intKIM_reg(void);
extern void _pyr2pyrFENG_reg(void);
extern void _pyr2pyrKIM_reg(void);
extern void _sahp_reg(void);
extern void _sahpNE_reg(void);
extern void _shock2int_reg(void);
extern void _shock2pyr_reg(void);
extern void _synapse_inter2pyr_reg(void);
extern void _tone2pyr_reg(void);
extern void _vecevent_reg(void);
extern void _xtra_reg(void);
extern void _xtra_imemrec_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," modfiles//CaDynamics.mod");
    fprintf(stderr," modfiles//Ca_HVA.mod");
    fprintf(stderr," modfiles//Ca_LVA.mod");
    fprintf(stderr," modfiles//Gfluct_new_exc.mod");
    fprintf(stderr," modfiles//Gfluct_new_inh.mod");
    fprintf(stderr," modfiles//Ih.mod");
    fprintf(stderr," modfiles//Im_v2.mod");
    fprintf(stderr," modfiles//K_P.mod");
    fprintf(stderr," modfiles//K_T.mod");
    fprintf(stderr," modfiles//Kd.mod");
    fprintf(stderr," modfiles//Kv2like.mod");
    fprintf(stderr," modfiles//Kv3_1.mod");
    fprintf(stderr," modfiles//MyExp2Sid.mod");
    fprintf(stderr," modfiles//NaTa.mod");
    fprintf(stderr," modfiles//NaTs.mod");
    fprintf(stderr," modfiles//NaV.mod");
    fprintf(stderr," modfiles//OLM_IA.mod");
    fprintf(stderr," modfiles//OLM_Ih.mod");
    fprintf(stderr," modfiles//OLM_Lca.mod");
    fprintf(stderr," modfiles//OLM_cat.mod");
    fprintf(stderr," modfiles//OLM_ccanl.mod");
    fprintf(stderr," modfiles//OLM_ichan2.mod");
    fprintf(stderr," modfiles//OLM_nap.mod");
    fprintf(stderr," modfiles//OLM_sahp.mod");
    fprintf(stderr," modfiles//SK.mod");
    fprintf(stderr," modfiles//bg2pyr.mod");
    fprintf(stderr," modfiles//ca.mod");
    fprintf(stderr," modfiles//cad.mod");
    fprintf(stderr," modfiles//cadyn.mod");
    fprintf(stderr," modfiles//cal2.mod");
    fprintf(stderr," modfiles//capool.mod");
    fprintf(stderr," modfiles//cav31.mod");
    fprintf(stderr," modfiles//function_TMonitor.mod");
    fprintf(stderr," modfiles//gabaa.mod");
    fprintf(stderr," modfiles//gap.mod");
    fprintf(stderr," modfiles//h.mod");
    fprintf(stderr," modfiles//halfgap.mod");
    fprintf(stderr," modfiles//im.mod");
    fprintf(stderr," modfiles//int2intFENG.mod");
    fprintf(stderr," modfiles//int2pyrFENG.mod");
    fprintf(stderr," modfiles//int2pyrKIM.mod");
    fprintf(stderr," modfiles//kadist.mod");
    fprintf(stderr," modfiles//kaprox.mod");
    fprintf(stderr," modfiles//kca.mod");
    fprintf(stderr," modfiles//kdrca1.mod");
    fprintf(stderr," modfiles//kdrca1DA.mod");
    fprintf(stderr," modfiles//kdrinter.mod");
    fprintf(stderr," modfiles//kdrinter_WB.mod");
    fprintf(stderr," modfiles//km.mod");
    fprintf(stderr," modfiles//kv.mod");
    fprintf(stderr," modfiles//leak.mod");
    fprintf(stderr," modfiles//leakDA.mod");
    fprintf(stderr," modfiles//leakinter.mod");
    fprintf(stderr," modfiles//na.mod");
    fprintf(stderr," modfiles//na12.mod");
    fprintf(stderr," modfiles//na16.mod");
    fprintf(stderr," modfiles//na3.mod");
    fprintf(stderr," modfiles//na3DA.mod");
    fprintf(stderr," modfiles//nainter.mod");
    fprintf(stderr," modfiles//nainter_WB.mod");
    fprintf(stderr," modfiles//nap.mod");
    fprintf(stderr," modfiles//nap2.mod");
    fprintf(stderr," modfiles//nat.mod");
    fprintf(stderr," modfiles//pyr2intFENG.mod");
    fprintf(stderr," modfiles//pyr2intKIM.mod");
    fprintf(stderr," modfiles//pyr2pyrFENG.mod");
    fprintf(stderr," modfiles//pyr2pyrKIM.mod");
    fprintf(stderr," modfiles//sahp.mod");
    fprintf(stderr," modfiles//sahpNE.mod");
    fprintf(stderr," modfiles//shock2int.mod");
    fprintf(stderr," modfiles//shock2pyr.mod");
    fprintf(stderr," modfiles//synapse_inter2pyr.mod");
    fprintf(stderr," modfiles//tone2pyr.mod");
    fprintf(stderr," modfiles//vecevent.mod");
    fprintf(stderr," modfiles//xtra.mod");
    fprintf(stderr," modfiles//xtra_imemrec.mod");
    fprintf(stderr, "\n");
  }
  _CaDynamics_reg();
  _Ca_HVA_reg();
  _Ca_LVA_reg();
  _Gfluct_new_exc_reg();
  _Gfluct_new_inh_reg();
  _Ih_reg();
  _Im_v2_reg();
  _K_P_reg();
  _K_T_reg();
  _Kd_reg();
  _Kv2like_reg();
  _Kv3_1_reg();
  _MyExp2Sid_reg();
  _NaTa_reg();
  _NaTs_reg();
  _NaV_reg();
  _OLM_IA_reg();
  _OLM_Ih_reg();
  _OLM_Lca_reg();
  _OLM_cat_reg();
  _OLM_ccanl_reg();
  _OLM_ichan2_reg();
  _OLM_nap_reg();
  _OLM_sahp_reg();
  _SK_reg();
  _bg2pyr_reg();
  _ca_reg();
  _cad_reg();
  _cadyn_reg();
  _cal2_reg();
  _capool_reg();
  _cav31_reg();
  _function_TMonitor_reg();
  _gabaa_reg();
  _gap_reg();
  _h_reg();
  _halfgap_reg();
  _im_reg();
  _int2intFENG_reg();
  _int2pyrFENG_reg();
  _int2pyrKIM_reg();
  _kadist_reg();
  _kaprox_reg();
  _kca_reg();
  _kdrca1_reg();
  _kdrca1DA_reg();
  _kdrinter_reg();
  _kdrinter_WB_reg();
  _km_reg();
  _kv_reg();
  _leak_reg();
  _leakDA_reg();
  _leakinter_reg();
  _na_reg();
  _na12_reg();
  _na16_reg();
  _na3_reg();
  _na3DA_reg();
  _nainter_reg();
  _nainter_WB_reg();
  _nap_reg();
  _nap2_reg();
  _nat_reg();
  _pyr2intFENG_reg();
  _pyr2intKIM_reg();
  _pyr2pyrFENG_reg();
  _pyr2pyrKIM_reg();
  _sahp_reg();
  _sahpNE_reg();
  _shock2int_reg();
  _shock2pyr_reg();
  _synapse_inter2pyr_reg();
  _tone2pyr_reg();
  _vecevent_reg();
  _xtra_reg();
  _xtra_imemrec_reg();
}
