#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/opt/anaconda3/envs/neuro/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/opt/anaconda3/envs/neuro/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/gregglickert/Documents/GitHub/PlasticityToy/1_cell_model/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
