#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _CaDynamics_reg();
extern void _Ca_HVA_reg();
extern void _Ca_LVA_reg();
extern void _Gfluct_new_exc_reg();
extern void _Gfluct_new_inh_reg();
extern void _Ih_reg();
extern void _Im_v2_reg();
extern void _K_P_reg();
extern void _K_T_reg();
extern void _Kd_reg();
extern void _Kv2like_reg();
extern void _Kv3_1_reg();
extern void _MyExp2Sid_reg();
extern void _NaTa_reg();
extern void _NaTs_reg();
extern void _NaV_reg();
extern void _SK_reg();
extern void _bg2pyr_reg();
extern void _ca_reg();
extern void _cad_reg();
extern void _cadyn_reg();
extern void _cal2_reg();
extern void _capool_reg();
extern void _cav31_reg();
extern void _function_TMonitor_reg();
extern void _gabaa_reg();
extern void _gap_reg();
extern void _h_reg();
extern void _halfgap_reg();
extern void _im_reg();
extern void _interD2interD_STFD_new_reg();
extern void _interD2pyrD_STFD_new_reg();
extern void _kadist_reg();
extern void _kaprox_reg();
extern void _kca_reg();
extern void _kdrca1_reg();
extern void _kdrca1DA_reg();
extern void _kdrinter_reg();
extern void _kdrinter_WB_reg();
extern void _km_reg();
extern void _kv_reg();
extern void _leak_reg();
extern void _leakDA_reg();
extern void _leakinter_reg();
extern void _na_reg();
extern void _na12_reg();
extern void _na16_reg();
extern void _na3_reg();
extern void _na3DA_reg();
extern void _nainter_reg();
extern void _nainter_WB_reg();
extern void _nap_reg();
extern void _nap2_reg();
extern void _nat_reg();
extern void _pyr2pyr_reg();
extern void _pyrD2interD_STFD_reg();
extern void _pyrD2pyrD_STFD_new_reg();
extern void _sahp_reg();
extern void _sahpNE_reg();
extern void _shock2pyr_reg();
extern void _tone2pyr_reg();
extern void _vecevent_reg();
extern void _xtra_reg();
extern void _xtra_imemrec_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," CaDynamics.mod");
fprintf(stderr," Ca_HVA.mod");
fprintf(stderr," Ca_LVA.mod");
fprintf(stderr," Gfluct_new_exc.mod");
fprintf(stderr," Gfluct_new_inh.mod");
fprintf(stderr," Ih.mod");
fprintf(stderr," Im_v2.mod");
fprintf(stderr," K_P.mod");
fprintf(stderr," K_T.mod");
fprintf(stderr," Kd.mod");
fprintf(stderr," Kv2like.mod");
fprintf(stderr," Kv3_1.mod");
fprintf(stderr," MyExp2Sid.mod");
fprintf(stderr," NaTa.mod");
fprintf(stderr," NaTs.mod");
fprintf(stderr," NaV.mod");
fprintf(stderr," SK.mod");
fprintf(stderr," bg2pyr.mod");
fprintf(stderr," ca.mod");
fprintf(stderr," cad.mod");
fprintf(stderr," cadyn.mod");
fprintf(stderr," cal2.mod");
fprintf(stderr," capool.mod");
fprintf(stderr," cav31.mod");
fprintf(stderr," function_TMonitor.mod");
fprintf(stderr," gabaa.mod");
fprintf(stderr," gap.mod");
fprintf(stderr," h.mod");
fprintf(stderr," halfgap.mod");
fprintf(stderr," im.mod");
fprintf(stderr," interD2interD_STFD_new.mod");
fprintf(stderr," interD2pyrD_STFD_new.mod");
fprintf(stderr," kadist.mod");
fprintf(stderr," kaprox.mod");
fprintf(stderr," kca.mod");
fprintf(stderr," kdrca1.mod");
fprintf(stderr," kdrca1DA.mod");
fprintf(stderr," kdrinter.mod");
fprintf(stderr," kdrinter_WB.mod");
fprintf(stderr," km.mod");
fprintf(stderr," kv.mod");
fprintf(stderr," leak.mod");
fprintf(stderr," leakDA.mod");
fprintf(stderr," leakinter.mod");
fprintf(stderr," na.mod");
fprintf(stderr," na12.mod");
fprintf(stderr," na16.mod");
fprintf(stderr," na3.mod");
fprintf(stderr," na3DA.mod");
fprintf(stderr," nainter.mod");
fprintf(stderr," nainter_WB.mod");
fprintf(stderr," nap.mod");
fprintf(stderr," nap2.mod");
fprintf(stderr," nat.mod");
fprintf(stderr," pyr2pyr.mod");
fprintf(stderr," pyrD2interD_STFD.mod");
fprintf(stderr," pyrD2pyrD_STFD_new.mod");
fprintf(stderr," sahp.mod");
fprintf(stderr," sahpNE.mod");
fprintf(stderr," shock2pyr.mod");
fprintf(stderr," tone2pyr.mod");
fprintf(stderr," vecevent.mod");
fprintf(stderr," xtra.mod");
fprintf(stderr," xtra_imemrec.mod");
fprintf(stderr, "\n");
    }
_CaDynamics_reg();
_Ca_HVA_reg();
_Ca_LVA_reg();
_Gfluct_new_exc_reg();
_Gfluct_new_inh_reg();
_Ih_reg();
_Im_v2_reg();
_K_P_reg();
_K_T_reg();
_Kd_reg();
_Kv2like_reg();
_Kv3_1_reg();
_MyExp2Sid_reg();
_NaTa_reg();
_NaTs_reg();
_NaV_reg();
_SK_reg();
_bg2pyr_reg();
_ca_reg();
_cad_reg();
_cadyn_reg();
_cal2_reg();
_capool_reg();
_cav31_reg();
_function_TMonitor_reg();
_gabaa_reg();
_gap_reg();
_h_reg();
_halfgap_reg();
_im_reg();
_interD2interD_STFD_new_reg();
_interD2pyrD_STFD_new_reg();
_kadist_reg();
_kaprox_reg();
_kca_reg();
_kdrca1_reg();
_kdrca1DA_reg();
_kdrinter_reg();
_kdrinter_WB_reg();
_km_reg();
_kv_reg();
_leak_reg();
_leakDA_reg();
_leakinter_reg();
_na_reg();
_na12_reg();
_na16_reg();
_na3_reg();
_na3DA_reg();
_nainter_reg();
_nainter_WB_reg();
_nap_reg();
_nap2_reg();
_nat_reg();
_pyr2pyr_reg();
_pyrD2interD_STFD_reg();
_pyrD2pyrD_STFD_new_reg();
_sahp_reg();
_sahpNE_reg();
_shock2pyr_reg();
_tone2pyr_reg();
_vecevent_reg();
_xtra_reg();
_xtra_imemrec_reg();
}
